# Generated by Django 4.1 on 2023-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="food",
            field=models.CharField(
                choices=[("5", "Amazing"), ("3", "Decent"), ("1", "Disappointing")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="name",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="review",
            name="price",
            field=models.CharField(
                choices=[("5", "Amazing"), ("3", "Decent"), ("1", "Disappointing")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="speed",
            field=models.CharField(
                choices=[("5", "Amazing"), ("3", "Decent"), ("1", "Disappointing")],
                default="",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
